import {$,heading,panel,badge} from './ui.js';
const blocks=[
  ['Источники данных','SCADA · MES · ERP · IoT','roadmap','Подключение OPC UA / MQTT, события оборудования, производственные задания и складские остатки. В MVP используются неизменяемые данные кейса и отдельный генератор. Реальные подключения не выполняются.'],
  ['Приём и проверка','Seed · симулятор · правила','mvp','Идемпотентная загрузка исходных таблиц. 60 дней синтетической истории с фиксированным seed. Валидация параметров через Pydantic. Флаги качества данных: период смены и расхождение 4 800 / 5 500. Промышленная шина событий — следующий этап.'],
  ['Хранилище','SQLAlchemy · SQLite / PostgreSQL','mvp','Нормализованные таблицы участков, оборудования, выпуска, качества, простоев, планов и инцидентов. JSON-снимки отдельной live-симуляции. SQLite для демо; DATABASE_URL для PostgreSQL. Исходные записи не перезаписываются.'],
  ['Аналитика и ML','KPI · регрессия · аномалии','mvp','OEE по методике задания, пороговые правила, логистическая регрессия риска, объяснения через стандартизованные коэффициенты. Прогноз выпуска: линейная регрессия и бутстрэп. Z-score качества и загрузки. Результаты кэшируются.'],
  ['API и интерфейс','FastAPI · WebSocket · SVG','mvp','REST API /api, OpenAPI /docs, WebSocket /ws/live с heartbeat. HTML/CSS/JS без сборки, локальные шрифты. Переподключение, встроенный снимок, локальный симулятор и Service Worker для повторного открытия без сервера.'],
  ['Уведомления и действия','Инциденты · Telegram · e-mail','mixed','В MVP: журнал, уведомления в интерфейсе, принятие в работу, закрытие и рекомендации. В дорожной карте: Telegram/e-mail, назначение ответственных, интеграция с заявками на ремонт. Внешние сообщения не отправляются.']
];
export function renderArchitecture(){
  $('#content').innerHTML=heading('ОТ ПРОТОТИПА К ПРОМЫШЛЕННОЙ СИСТЕМЕ','Архитектура решения','Нажмите на блок, чтобы увидеть его роль, реализацию и границы MVP.')+`<div class="architecture-grid">${blocks.map((b,i)=>`<button class="arch-card" data-arch="${i}"><div class="step">0${i+1} ${i<5?'→':'↗'}</div><h2>${b[0]}</h2><p>${b[1]}</p>${badge(b[2]==='roadmap'?'maintenance':'normal',b[2]==='roadmap'?'В дорожной карте':b[2]==='mixed'?'MVP + дорожная карта':'Реализовано в MVP')}</button>`).join('')}</div><div id="arch-detail" class="panel arch-detail">Выберите компонент архитектуры.</div><div class="section-space">${panel('Поток данных',`<div class="panel-body"><p class="subtitle">Источники → приём и проверка → хранилище → аналитика → API / WebSocket → интерфейс → действие.</p><p class="subtitle">Внешние интеграции обозначены в дорожной карте. Демо работает одним сервисом, без облачных ключей и внешних запросов из интерфейса.</p><div class="filters section-space"><a href="/docs" target="_blank" rel="noopener" class="button">Открыть OpenAPI ↗</a><a href="/api/health" target="_blank" rel="noopener" class="button">Состояние сервера ↗</a></div></div>`)}</div>`;
  document.querySelectorAll('[data-arch]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-arch]').forEach(x=>x.classList.toggle('active',x===b));const block=blocks[+b.dataset.arch];$('#arch-detail').innerHTML=`<h2>${block[0]}</h2><p>${block[3]}</p>`;});document.querySelector('[data-arch]').click();
}
