import {post} from './api.js';
import {$,esc,fmt,money,heading,panel} from './ui.js';
import {lineChart} from './charts.js';
let inputs={downtime_reduction_pct:20,defect_reduction_pct:25,downtime_cost_per_hour:150000,defect_cost_per_car:80000,implementation_cost:15000000,operating_days_per_year:250},timer,sequence=0;
const fields=[['downtime_reduction_pct','Сокращение неплановых простоев',0,100,1,'%'],['defect_reduction_pct','Снижение числа дефектов',0,100,1,'%'],['downtime_cost_per_hour','Стоимость часа простоя оборудования',0,1000000,10000,'₸'],['defect_cost_per_car','Стоимость одного дефекта / исправления',0,500000,5000,'₸'],['implementation_cost','Стоимость внедрения',0,50000000,500000,'₸'],['operating_days_per_year','Рабочих дней в году',1,366,1,'дней']];
export async function renderImpact(){
  $('#content').innerHTML=heading('ЭКОНОМИКА РЕШЕНИЯ','Эффект для бизнеса','Оцените потенциал улучшений на прозрачных, изменяемых допущениях.',`<span class="badge demo">Расчётный сценарий</span>`)+`<div class="impact-grid">${panel('Параметры сценария',`<div class="panel-body">${fields.map(([key,label,min,max,step,unit])=>`<div class="slider-field"><label for="${key}">${label}<output id="${key}-value">${fmt(inputs[key])} ${unit}</output></label><input id="${key}" data-impact-key="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${inputs[key]}"><div class="slider-scale"><span>${fmt(min)}</span><span>${fmt(max)} ${unit}</span></div></div>`).join('')}<button id="impact-defaults" class="button small">↺ Вернуть допущения</button></div>`)}<div id="impact-result"></div></div>`;
  fields.forEach(([key,,,,,unit])=>$('#'+key).oninput=e=>{inputs[key]=+e.target.value;$('#'+key+'-value').textContent=fmt(inputs[key])+' '+unit;clearTimeout(timer);timer=setTimeout(update,140);});$('#impact-defaults').onclick=()=>{inputs={downtime_reduction_pct:20,defect_reduction_pct:25,downtime_cost_per_hour:150000,defect_cost_per_car:80000,implementation_cost:15000000,operating_days_per_year:250};renderImpact();};await update();
}
async function update(){const version=++sequence;try{const d=await post('/api/impact',inputs);if(version!==sequence||!$('#impact-result'))return;$('#impact-result').innerHTML=`<div class="impact-total"><p class="eyebrow">ПОТЕНЦИАЛЬНАЯ ГОДОВАЯ ЭКОНОМИЯ</p><div class="value-large">${fmt(d.annual_savings/1000000,2)} <small>млн ₸ / год</small></div><p>Сценарная оценка. Не гарантированный экономический эффект.</p></div><div class="impact-split"><div class="panel"><div class="panel-body"><span class="muted small-text">Сокращение простоев</span><strong>${fmt(d.downtime_savings/1000000,2)} <small>млн ₸</small></strong></div></div><div class="panel"><div class="panel-body"><span class="muted small-text">Снижение дефектов</span><strong>${fmt(d.quality_savings/1000000,2)} <small>млн ₸</small></strong></div></div></div>${panel('Чувствительность к сокращению простоев',`<div class="panel-body">${lineChart(d.curve.map(r=>({label:r.reduction_pct+'%',saving:r.annual_savings/1000000})),[{key:'saving',label:'Экономия, млн ₸ · модель',tone:'model'}],{height:170})}<p class="subtitle small-text">По горизонтали — сокращение простоев, %. По вертикали — общая экономия, млн ₸/год. Остальные параметры зафиксированы.</p></div>`)}<div class="section-space">${panel('Окупаемость и допущения',`<div class="panel-body"><div class="value-large">${d.payback_months===null?'—':fmt(d.payback_months,1)} <small>месяцев</small></div><p class="subtitle small-text">${d.payback_months===null?'При нулевой экономии окупаемость не определяется.':'Простая окупаемость при затратах '+money(inputs.implementation_cost)}</p><ul class="assumptions">${d.assumptions.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></div>`)}</div>`;}catch(e){if($('#impact-result'))$('#impact-result').innerHTML=`<div class="error">${esc(e.message)}</div>`;}}
