import {api,post} from './api.js';
import {$,esc,fmt,heading,panel,badge,names,dateLabel,toast,empty} from './ui.js';
let filter={};
export async function renderIncidents(){
  $('#content').innerHTML=heading('КОНТРОЛЬ ОТКЛОНЕНИЙ','Инциденты','История сигналов, работа с причинами и контроль решений.')+`<div class="filters"><select id="filter-stage" aria-label="Участок"><option value="">Все участки</option>${Object.entries(names).map(([c,n])=>`<option value="${c}">${n}</option>`).join('')}</select><select id="filter-severity" aria-label="Критичность"><option value="">Любая критичность</option><option value="critical">Критично</option><option value="warning">Предупреждение</option><option value="info">Информация</option></select><select id="filter-status" aria-label="Статус"><option value="">Все статусы</option><option value="open">Открыт</option><option value="ack">В работе</option><option value="resolved">Закрыт</option></select><input type="date" id="filter-from" aria-label="Дата от"><input type="date" id="filter-to" aria-label="Дата до"><button class="button small" id="filter-reset">Сбросить фильтры</button></div>${panel('Журнал событий','<div id="incident-table"></div>',`<span id="incident-count" class="badge info">Загрузка</span>`)}<p class="subtitle small-text">Кейс — исходные наблюдения. Симулятор и ИИ — демонстрационные сигналы. Принятие и закрытие сохраняются в базе; офлайн — в памяти текущей вкладки.</p>`;
  ['stage','severity','status','from','to'].forEach(k=>{$('#filter-'+k).value=filter[k]||'';$('#filter-'+k).onchange=()=>{filter[k]=$('#filter-'+k).value;loadIncidents().catch(e=>toast(e.message));};});$('#filter-reset').onclick=()=>{filter={};renderIncidents().catch(e=>toast(e.message));};await loadIncidents();
}
export async function loadIncidents(){if(!$('#incident-table'))return;const qs=new URLSearchParams(Object.entries(filter).filter(([,v])=>v)),d=await api('/api/incidents?'+qs);if(!$('#incident-table'))return;$('#incident-count').textContent=fmt(d.items.length)+' событий';$('#incident-table').innerHTML=d.items.length?`<div class="table-scroll"><table><thead><tr><th>Дата / источник</th><th>Инцидент</th><th>Критичность</th><th>Статус</th><th>Действие</th></tr></thead><tbody>${d.items.map(i=>`<tr class="clickable" data-open-stage="${esc(i.stage||'assembly')}"><td>${dateLabel(i.created_at)}<br>${badge(i.is_demo?'demo':'info',i.source==='ai'?'ИИ · демо':i.source==='simulator'?'Симулятор':'Кейс')}</td><td><strong>${esc(i.title)}</strong><br><span class="muted">${esc(i.stage_name)}</span></td><td>${badge(i.severity)}</td><td>${badge(i.status)}</td><td><div class="table-actions">${i.status==='open'?`<button class="button small" data-incident-action="ack" data-id="${i.id}">Принять в работу</button>`:''}${i.status!=='resolved'?`<button class="button small ghost" data-incident-action="resolve" data-id="${i.id}">Закрыть</button>`:'—'}</div></td></tr>`).join('')}</tbody></table></div>`:empty('Нет инцидентов по выбранным фильтрам');}
export async function actOnIncident(id,action){await post(`/api/incidents/${id}/${action}`);toast(action==='ack'?'Инцидент принят в работу':'Инцидент закрыт');await loadIncidents();}
