import {$,esc,fmt,heading,kpi,panel,badge,demo,empty,names,states,panelTop,openPanel,loading,error,aiNotice,dateLabel} from './ui.js';
import {lineChart} from './charts.js';
import {api} from './api.js';
let currentPlant=null,animationStarted=false,historyTimes=[],historical=false;
const statusColor=s=>['down','critical'].includes(s)?'#ff7065':s==='warning'?'#e8be62':s==='idle'?'#aca08e':s==='maintenance'?'#9399a5':'#60d8a4';
const formatTime=at=>at?.slice(11,16)||'—';
export const isHistorical=()=>historical;
export function exitHistory(){historical=false;}
export function plantPage(){return heading('ПРОИЗВОДСТВО В РЕАЛЬНОМ ВРЕМЕНИ','Схема завода','Весь производственный поток. Отклонения, оборудование и решения — в одном месте.',`<div class="date-chip"><span class="dot"></span><span id="virtual-clock">Демо-смена · 03 окт, 12:00</span></div>`)+
  '<div id="snapshot-banner"></div><div id="plant-kpis" class="kpi-strip"></div>'+panel('Производственный поток',`<div id="plant-map" class="map-wrap">${loading()}</div><div class="map-legend"><span class="legend-item"><i class="legend-dot"></i>Работает</span><span class="legend-item warning"><i class="legend-dot"></i>Предупреждение</span><span class="legend-item critical"><i class="legend-dot"></i>Авария / отклонение</span><span class="legend-item maintenance"><i class="legend-dot"></i>Плановое ТО</span><span class="right">Нажмите на участок или оборудование ↗</span></div><div class="timeline"><span>◷ Назад во времени</span><strong id="timeline-time">LIVE</strong><input id="timeline-slider" type="range" min="0" max="0" value="0" aria-label="Выбрать снимок завода"><button id="timeline-live" class="button small">В эфир</button></div>`,
  `<div class="simulation-controls"><label class="switch-label"><input id="simulation-toggle" type="checkbox" checked>Live-симуляция</label><div class="segmented" aria-label="Скорость симуляции"><button data-speed="1" class="active">×1</button><button data-speed="5">×5</button><button data-speed="20">×20</button></div></div>`,'map-panel')+
  `<div class="grid-two">${panel('Сценарии для демонстрации',`<div class="scenario-list"><button class="scenario-card" data-scenario="conveyor_failure"><span class="scenario-icon">⚒</span><strong>Поломка конвейера</strong><small>Остановка и каскад буферов</small></button><button class="scenario-card" data-scenario="paint_defect_spike"><span class="scenario-icon">◉</span><strong>Всплеск брака</strong><small>Окраска · до 8% дефектов</small></button><button class="scenario-card" data-scenario="supply_disruption"><span class="scenario-icon">▧</span><strong>Сбой поставки</strong><small>Нехватка комплектующих</small></button></div><div class="scenario-note">Сценарии меняют демонстрационный поток. Для быстрого каскада выберите ×20.</div>`,`<button class="button link" data-scenario="reset">↺ Сбросить</button>`)}${panel('Требует внимания',`<div id="plant-insights">${loading()}</div>`,`<span class="badge info">Данные кейса + демо</span>`)}</div><p class="subtitle small-text">LIVE — отдельная демонстрационная смена. В карточках участков: исходные записи 1–2 октября и явно помеченная синтетическая история.</p>`;}
function stageIcon(type,x,y){if(type==='warehouse')return `<path d="M${x} ${y+14} l20 -12 20 12 v29 h-40z M${x+9} ${y+43} v-20 h22 v20 M${x+16} ${y+23} v20 M${x+24} ${y+23} v20" fill="none" stroke="#697589" stroke-width="1.5"/>`;if(type==='quality')return `<circle cx="${x+20}" cy="${y+23}" r="20" fill="none" stroke="#697589" stroke-width="1.5"/><path d="M${x+10} ${y+24} l7 7 15 -17" fill="none" stroke="#697589" stroke-width="2"/>`;return '';}
export function mapSVG(plant){const W=1170,H=268,cw=166,gap=28,positions=plant.stages.map((s,i)=>({s,x:17+i*(cw+gap)}));const prod=plant.stages.filter(s=>s.type==='production');const limiting=[...prod].sort((a,b)=>(a.kpi.rate_per_hour*(1-a.kpi.defect_pct/100)-b.kpi.rate_per_hour*(1-b.kpi.defect_pct/100))||(Number(a.kpi.status!=='down')-Number(b.kpi.status!=='down')))[0]?.code;
  let svg=`<svg class="plant-svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="Интерактивная схема автомобильного завода"><defs><marker id="arrow" markerWidth="5" markerHeight="5" refX="4" refY="2.5" orient="auto"><path d="M0 0 L5 2.5 L0 5" fill="#697488"/></marker></defs>`;
  for(let i=0;i<positions.length-1;i++){const {s,x}=positions[i],next=positions[i+1],stopped=['down','idle'].includes(s.kpi.status)||['down','idle'].includes(next.s.kpi.status);svg+=`<path class="flow-line" d="M${x+cw} 129 H${next.x-4}" marker-end="url(#arrow)"/><circle class="flow-dot" data-flow-start="${x+cw+3}" data-flow-end="${next.x-5}" data-flow-rate="${Math.max(.1,Math.min(s.kpi.load_pct??100,next.s.kpi.load_pct??100)/100)}" data-moving="${stopped?0:1}" cx="${x+cw+3}" cy="129" r="2" style="fill:${stopped?'#5a5f6c':'#62d4a3'}"/>`;}
  for(const {s,x} of positions){const k=s.kpi,status=k.status||'running';svg+=`<g class="stage-node status-${esc(status)}" data-stage="${s.code}" tabindex="0" role="button" aria-label="${esc(s.name)}: ${esc(k.status_label||states[status])}"><title>${esc(s.name)} · ${esc(k.status_label||states[status])} · нажмите для детализации</title><rect class="stage-bg" x="${x}" y="45" width="${cw}" height="176" rx="8"/><text class="stage-index" x="${x+13}" y="64">0${s.order+1} / ${s.type==='production'?'ПРОИЗВОДСТВО':s.type==='quality'?'КАЧЕСТВО':'ЛОГИСТИКА'}</text><text class="stage-name" x="${x+13}" y="85">${s.code==='parts'?'Комплектующие':s.name}</text><circle cx="${x+16}" cy="102" r="2.3" fill="${statusColor(status)}"/><text class="stage-status" x="${x+23}" y="105">${esc((k.status_label||states[status]).slice(0,25))}</text>`;
    if(s.type==='production'){
      s.equipment.forEach((e,i)=>{const ex=x+13+(i%4)*36;svg+=`<g class="equipment-node" data-equipment="${esc(e.code)}" tabindex="0" role="button" aria-label="${esc(e.code)}"><title>${esc(e.code)} · ${esc(states[e.status]||e.status)}</title><rect x="${ex}" y="122" width="28" height="28" rx="4" style="stroke:${statusColor(e.status)}80"/><path d="M${ex+5} 142 l5 -10 6 4 6 -10 M${ex+10} 132 v-4 M${ex+8} 144 h13" stroke="${statusColor(e.status)}" fill="none" stroke-width="1.4"/><text x="${ex+14}" y="161" text-anchor="middle">${esc(e.code.split('-').at(-1).slice(0,5))}</text></g>`;});
      svg+=`<text class="stage-number" x="${x+13}" y="190">${fmt(k.fact)}<tspan fill="#858d9e" font-size="10"> / ${k.plan}</tspan></text><text class="stage-small" x="${x+13}" y="205">ВЫПУСК / ПЛАН СУТОК</text><text class="stage-stat" x="${x+cw-13}" y="188" text-anchor="end">${fmt(k.load_pct)}%</text><text class="stage-small" x="${x+cw-13}" y="204" text-anchor="end">ЗАГРУЗКА</text>`;
    }else{svg+=stageIcon(s.type,x+14,117)+`<text class="stage-number" x="${x+cw-14}" y="145" text-anchor="end">${fmt(k.inventory)}</text><text class="stage-small" x="${x+cw-14}" y="161" text-anchor="end">${s.code==='parts'?'КОМПЛЕКТОВ':s.code==='quality'?'ПРИНЯТО':'АВТОМОБИЛЕЙ'}</text><text class="stage-small" x="${x+13}" y="199">ДЕМО-ДАННЫЕ</text>`;if(s.equipment.length)svg+=`<g class="equipment-node" data-equipment="${esc(s.equipment[0].code)}" role="button" tabindex="0" aria-label="${esc(s.equipment[0].code)}"><rect x="${x+78}" y="179" width="73" height="19" rx="3"/><text x="${x+114}" y="191" text-anchor="middle">Стенд-геометрии</text></g>`;}
    svg+='</g>';if(s.code===limiting)svg+=`<rect class="bottleneck-outline" x="${x-4}" y="41" width="${cw+8}" height="184" rx="11"/><text x="${x+cw/2}" y="30" fill="#ff8275" font-size="9" text-anchor="middle">◆ УЗКОЕ МЕСТО · ДЕМО</text>`;
  }
  for(const b of plant.state.buffers){const left=positions.find(p=>p.s.code===b.from_stage),bx=left.x+cw+gap/2;svg+=`<g><title>Буфер: ${fmt(b.qty,1)} / ${b.capacity}; прирост ${fmt(b.growth_per_min,2)} ед/мин</title><text class="buffer-label" x="${bx}" y="240" text-anchor="middle">БУФЕР</text><text class="buffer-value" x="${bx}" y="256" text-anchor="middle">${fmt(b.qty,1)} / ${b.capacity}</text><rect x="${bx-22}" y="224" width="44" height="3" rx="1.5" fill="#38404a"/><rect x="${bx-22}" y="224" width="${Math.max(0,Math.min(44,b.qty/b.capacity*44))}" height="3" rx="1.5" fill="${b.qty/b.capacity>.85?'#ff7667':'#6b8c9e'}"/></g>`;}
  return svg+'</svg>';}
function animate(time){if(!matchMedia('(prefers-reduced-motion: reduce)').matches)document.querySelectorAll('.flow-dot[data-moving="1"]').forEach((el,i)=>{const start=+el.dataset.flowStart,end=+el.dataset.flowEnd;el.setAttribute('cx',start+(end-start)*((time/1500*(+el.dataset.flowRate||1)+i*.2)%1));});requestAnimationFrame(animate);}
export function updatePlant(plant,force=false){if(historical&&!force)return;currentPlant=plant;const state=plant.state,stages=Object.values(state.stages),a=state.stages.assembly,limiting=[...stages].sort((a,b)=>(a.rate_per_hour*(1-a.defect_pct/100)-b.rate_per_hour*(1-b.defect_pct/100))||(Number(a.status!=='down')-Number(b.status!=='down')))[0];
  if($('#plant-kpis'))$('#plant-kpis').innerHTML=kpi('Выпуск сборки',fmt(a.fact),'авто',`Демо-сутки · план ${a.plan}`,'▱')+kpi('OEE потока · LIVE',fmt(limiting?.oee,1),'%',`Оперативная модель · цель ≥85%`,'◴',limiting?.oee<85?'yellow':'')+kpi('Брак на окраске',fmt(state.stages.painting.defect_pct,2),'%',`Допуск ≤2% · демо-поток`,'◉','red')+kpi('Простои участков',fmt(stages.reduce((s,x)=>s+x.downtime_min,0)),'мин','Сумма остановок · демо','◷')+kpi('Активные инциденты',fmt(state.incident_count),'',`Исходные данные + симуляция`,'△',state.incident_count?'yellow':'');
  if($('#plant-map'))$('#plant-map').innerHTML=mapSVG(plant);
  if($('#virtual-clock'))$('#virtual-clock').textContent=`Демо · ${state.at.slice(8,10)} окт, ${formatTime(state.at)}`;
  if(!animationStarted){animationStarted=true;requestAnimationFrame(animate);}
}
export async function loadPlant(){const [plant,simulation,dashboard]=await Promise.all([api('/api/plant'),api('/api/simulation'),api('/api/dashboard')]);updatePlant(plant);if($('#simulation-toggle'))$('#simulation-toggle').checked=simulation.enabled;document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',+b.dataset.speed===simulation.speed));renderInsights(dashboard.decisions);await refreshTimeline();return plant;}
export function renderInsights(items){if(!$('#plant-insights'))return;$('#plant-insights').innerHTML=items.slice(0,2).map(i=>`<div class="insight-row"><div class="insight-icon">!</div><div><h3>${esc(i.title)}</h3><p>${esc(i.description)}</p></div><button class="button link" data-open-stage="${esc(i.stage||'painting')}" aria-label="Открыть ${esc(i.stage_name)}">↗</button></div>`).join('')||empty('Активных отклонений нет');}
export async function refreshTimeline(){if(!$('#timeline-slider'))return;const t=await api('/api/timeline');historyTimes=t.available;const slider=$('#timeline-slider');if(slider){slider.max=Math.max(0,historyTimes.length-1);if(!historical)slider.value=slider.max;}}
export async function selectSnapshot(index){if(!historyTimes[index])return;const t=await api('/api/timeline?at='+encodeURIComponent(historyTimes[index]));historical=true;updatePlant(t.plant,true);$('#timeline-time').textContent=formatTime(t.at);$('#snapshot-banner').innerHTML=`<div class="snapshot-banner">◷ Снимок ${dateLabel(t.at)} · отображение зафиксировано. Детализация участков содержит исходную историю; вернитесь «В эфир» для текущего потока.</div>`;}
export function showLive(){historical=false;if($('#snapshot-banner'))$('#snapshot-banner').innerHTML='';if($('#timeline-time'))$('#timeline-time').textContent='LIVE';return loadPlant();}
export async function showStage(code,includeSynthetic=false){openPanel(panelTop(names[code]||code)+loading());try{const d=await api('/api/stages/'+encodeURIComponent(code));const s=currentPlant?.stages.find(x=>x.code===code);let html=panelTop(d.stage.name);
    if(d.is_demo){const k=s?.kpi||{};html+=`${demo}<p class="subtitle">Упрощённая модель ${code==='quality'?'контроля качества':'склада'}.</p><div class="value-large section-space">${fmt(k.inventory)} <small>${code==='parts'?'комплектов':'единиц'}</small></div><div class="notice info">Остатки и движение заданы симулятором. Реальных складских записей и результатов финального контроля в кейсе нет.</div>`;html+=(s?.equipment||[]).map(e=>`<button class="button" data-equipment="${esc(e.code)}">${esc(e.code)} ↗</button>`).join('');openPanel(html);return;}
    const k=d.kpi.stages[0],p=d.production.filter(r=>includeSynthetic||!r.is_synthetic),q=d.quality.filter(r=>includeSynthetic||!r.is_synthetic),downs=d.downtime.filter(r=>includeSynthetic||!r.is_synthetic);
    html+=`<div class="detail-meta"><div>Исходный период<strong>01–02 октября 2026</strong></div><div>Смена<strong>Не указана в кейсе</strong></div></div><div class="kpi-strip">${kpi('План / факт',`${k.fact}`,'',`План ${k.plan} · ${fmt(k.performance,1)}%`)}${kpi('Загрузка',fmt(k.load_pct,1),'%','Среднее за 2 дня')}${kpi('Простой',fmt(k.downtime_min),'мин','Минуты оборудования')}${kpi('Брак',fmt(k.defect_pct,2),'%',`${k.defects} из ${k.fact}`,'',k.defect_pct>2?'red':'')}${kpi('OEE кейса',fmt(k.oee,2),'%','По методике задания')}${kpi('Годные',fmt(k.good),'ед.','На данном переделе')}</div><div class="notice info">${esc(d.kpi.methodology)} Плановое ТО не вычитается повторно из указанного времени работы.</div><label class="switch-label small-text muted"><input id="history-toggle" type="checkbox" data-history-stage="${code}" ${includeSynthetic?'checked':''}>Показать 60 дней синтетической истории</label><div class="detail-section"><h3>План и факт ${includeSynthetic?'· синтетическая история + кейс':''}</h3><div class="chart-legend"><span><i class="plan"></i>План</span><span><i></i>Факт</span></div>${lineChart(p,[{key:'plan',label:'План',color:'#8e9bb1'},{key:'fact',label:'Факт'}])}</div><div class="detail-section"><h3>Доля брака</h3>${lineChart(q,[{key:'defect_pct',label:'Брак, %'}],{threshold:2,height:175})}</div><div class="detail-section"><h3>Оборудование</h3><div class="filters">${(s?.equipment||[]).map(e=>`<button class="button small" data-equipment="${esc(e.code)}">${esc(e.code)} ↗</button>`).join('')}</div></div><div class="detail-section"><h3>Простои оборудования</h3>${downs.length?`<div class="table-scroll"><table><thead><tr><th>Дата</th><th>Причина</th><th>Мин</th></tr></thead><tbody>${downs.slice(0,15).map(r=>`<tr><td>${r.started_at.slice(0,10)}<br>${r.is_synthetic?badge('synthetic','Синтетика'):r.is_demo?demo:''}</td><td>${esc(r.reason)}<br>${r.kind==='planned'?badge('maintenance','Плановое ТО'):''}</td><td>${fmt(r.duration_min)}</td></tr>`).join('')}</tbody></table></div>`:empty()}</div><div class="detail-section"><h3>Инциденты участка</h3>${d.incidents.filter(i=>i.status!=='resolved').slice(0,4).map(i=>`<div class="insight-row"><div><h3>${esc(i.title)}</h3><p>${esc(i.description)}</p></div>${badge(i.severity)}</div>`).join('')||empty()}</div><div class="detail-section"><h3>Прогноз ИИ</h3>${aiNotice}${d.forecast.slice(0,2).map(r=>`<div class="risk-card"><div class="risk-head"><strong>${esc(r.equipment)}</strong>${badge(r.risk_level,fmt(r.probability*100,1)+'% / 24 ч')}</div>${r.factors.map(f=>`<div class="risk-factor"><span>${esc(f.name)}</span><span>${fmt(f.value,1)} · ${esc(f.direction)}</span></div>`).join('')}</div>`).join('')}</div>`;
    openPanel(html);
  }catch(e){openPanel(panelTop(names[code]||code)+error(e));}}
export async function showEquipment(code){openPanel(panelTop(code)+loading());try{const d=await api('/api/equipment/'+encodeURIComponent(code));openPanel(panelTop(d.name)+badge(d.status)+` <span class="badge demo">Справочник · демо</span><div class="detail-meta section-space"><div>Критическое<strong>${d.critical?'Да · допущение':'Нет'}</strong></div><div>Последнее ТО<strong>${d.last_maintenance_at.slice(0,10)}</strong></div><div>После ТО<strong>${fmt(d.hours_since_maintenance)} ч</strong></div><div>MTBF · допущение<strong>${fmt(d.mtbf_hours)} ч</strong></div></div><div class="detail-section"><h3>Риск простоя в следующие 24 часа</h3>${aiNotice}<div class="value-large">${fmt(d.risk?.probability*100,1)}<small>%</small></div><p class="subtitle">${d.risk?.currently_down?'Оборудование уже остановлено. Вероятность модели не является оценкой текущего статуса.':'Сохранённая оценка демонстрационной модели.'}</p>${(d.risk?.factors||[]).map(f=>`<div class="risk-factor"><span>${esc(f.name)}</span><span>${fmt(f.value,1)} · ${esc(f.direction)}</span></div>`).join('')}</div><div class="detail-section"><h3>История простоев</h3><div class="table-scroll"><table><thead><tr><th>Дата</th><th>Причина</th><th>Мин</th></tr></thead><tbody>${d.downtime.map(r=>`<tr><td>${r.started_at.slice(0,10)}<br>${r.is_synthetic?badge('synthetic','Синтетика'):r.is_demo?demo:badge('info','Кейс')}</td><td>${esc(r.reason)}<br>${r.kind==='planned'?badge('maintenance'):''}</td><td>${fmt(r.duration_min)}</td></tr>`).join('')||'<tr><td colspan="3">Событий нет</td></tr>'}</tbody></table></div></div>`);}catch(e){openPanel(panelTop(code)+error(e));}}
