import {$,esc,fmt,heading,kpi,panel,badge,demo,empty,names,states,panelTop,openPanel,loading,error,aiNotice,dateLabel} from './ui.js';
import {lineChart} from './charts.js';
import {api} from './api.js';
import {iconDefs} from './icons.js';
let currentPlant=null,historyTimes=[],historical=false;
const statusColor=s=>['down','critical'].includes(s)?'var(--bad)':s==='warning'?'var(--yellow)':['idle','maintenance'].includes(s)?'var(--dim)':'var(--green)';
const displayName=s=>s.code==='parts'?'Склад комплектов':s.name;
const units={parts:'комплектов',quality:'принято',finished:'автомобилей'};
const formatTime=at=>at?.slice(11,16)||'—';
export const isHistorical=()=>historical;
export function exitHistory(){historical=false;}
export function plantPage(){return heading('ПРОИЗВОДСТВО В РЕАЛЬНОМ ВРЕМЕНИ','Схема завода','Весь производственный поток. Отклонения, оборудование и решения — в одном месте.',`<div class="date-chip"><span class="dot"></span><span id="virtual-clock">Демо-смена · 03 окт, 12:00</span></div>`)+
  '<div id="snapshot-banner"></div><div id="plant-kpis" class="kpi-strip"></div>'+panel('Производственный поток',`<div id="plant-map" class="map-wrap">${loading()}</div><div class="map-legend"><span class="legend-item"><i class="legend-dot"></i>Работает</span><span class="legend-item warning"><i class="legend-dot"></i>Риск</span><span class="legend-item critical"><i class="legend-dot"></i>Нарушение / остановка</span><span class="legend-item maintenance"><i class="legend-dot"></i>ТО / ожидание</span><span class="legend-item model"><b>61</b>модель (live-симуляция)</span><span class="right">Нажмите на участок или оборудование ↗</span></div><div class="timeline"><span>◷ Назад во времени</span><strong id="timeline-time">LIVE</strong><input id="timeline-slider" type="range" min="0" max="0" value="0" aria-label="Выбрать снимок завода"><button id="timeline-live" class="button small">В эфир</button></div>`,
  `<div class="simulation-controls"><label class="switch-label"><input id="simulation-toggle" type="checkbox" checked>Live-симуляция</label><div class="segmented" aria-label="Скорость симуляции"><button data-speed="1" class="active">×1</button><button data-speed="5">×5</button><button data-speed="20">×20</button></div></div>`,'map-panel')+
  `<div class="grid-two">${panel('Сценарии для демонстрации',`<div class="scenario-list"><button class="scenario-card" data-scenario="conveyor_failure"><span class="scenario-icon">⚒</span><strong>Поломка конвейера</strong><small>Остановка и каскад буферов</small></button><button class="scenario-card" data-scenario="paint_defect_spike"><span class="scenario-icon">◉</span><strong>Всплеск брака</strong><small>Окраска · до 8% дефектов</small></button><button class="scenario-card" data-scenario="supply_disruption"><span class="scenario-icon">▧</span><strong>Сбой поставки</strong><small>Нехватка комплектующих</small></button></div><div class="scenario-note">Сценарии меняют демонстрационный поток. Для быстрого каскада выберите ×20.</div>`,`<button class="button link" data-scenario="reset">↺ Сбросить</button>`)}${panel('Требует внимания',`<div id="plant-insights">${loading()}</div>`,`<span class="badge info">Данные кейса + демо</span>`)}</div><p class="subtitle small-text">LIVE — отдельная демонстрационная смена. В карточках участков: исходные записи 1–2 октября и явно помеченная синтетическая история.</p>`;}
const svgIcon=(name,cls)=>`<svg class="${cls}" aria-hidden="true" focusable="false"><use href="#icon-${name}"/></svg>`;
// Адаптивная сетка участков: 6 / 3 / 2 колонки по ширине контейнера (container queries в styles.css).
export function mapHTML(plant){const prod=plant.stages.filter(s=>s.type==='production');const limiting=[...prod].sort((a,b)=>(a.kpi.rate_per_hour*(1-a.kpi.defect_pct/100)-b.kpi.rate_per_hour*(1-b.kpi.defect_pct/100))||(Number(a.kpi.status!=='down')-Number(b.kpi.status!=='down')))[0]?.code;const now=performance.now()/1000;
  let html=`<svg class="icon-sprite" aria-hidden="true" width="0" height="0">${iconDefs()}</svg><div class="plant-flow" aria-label="Производственный поток: ${plant.stages.map(s=>esc(s.name)).join(' → ')}">`;
  plant.stages.forEach((s,i)=>{const k=s.kpi,status=k.status||'running',label=k.status_label||states[status],next=plant.stages[i+1],buffer=plant.state.buffers.find(b=>b.from_stage===s.code);
    let card=`<div class="stage-node status-${esc(status)}${s.code===limiting?' is-bottleneck':''}" data-stage="${s.code}" tabindex="0" role="button" aria-label="${esc(s.name)}: ${esc(label)}" title="${esc(s.name)} · ${esc(label)} · нажмите для детализации">${s.code===limiting?'<span class="bottleneck-label">Узкое место</span>':''}<div class="stage-head">${svgIcon(s.code,'stage-icon')}<span class="stage-index">0${s.order+1}</span></div><div class="stage-name">${esc(displayName(s))}</div><div class="stage-status" style="--status:${statusColor(status)}"><i></i>${esc(label)}</div><div class="equipment-row">`;
    card+=s.equipment.map(e=>{const es=states[e.status]||e.status;return `<span class="equipment-node" data-equipment="${esc(e.code)}" tabindex="0" role="button" aria-label="${esc(e.code)}: ${esc(es)}" title="${esc(e.code)} · ${esc(es)}" style="color:${statusColor(e.status)}">${svgIcon(e.status==='maintenance'?'wrench':'cog','equipment-icon')}</span>`;}).join('')+'</div>';
    card+=s.type==='production'?`<div class="stage-figures"><div class="stage-number">${fmt(k.fact)}<small> / ${k.plan}</small></div><div class="stage-small">выпуск / план</div><div class="stage-small"><b class="stage-stat">${fmt(k.load_pct)}%</b> загрузка</div></div>`:`<div class="stage-figures"><div class="stage-number">${fmt(k.inventory)}</div><div class="stage-small">${units[s.code]||'единиц'}</div></div>`;
    if(buffer){const ratio=Math.max(0,Math.min(1,buffer.qty/buffer.capacity));card+=`<div class="stage-buffer" title="Буфер: ${fmt(buffer.qty,1)} / ${buffer.capacity}; прирост ${fmt(buffer.growth_per_min,2)} ед/мин"><span class="buffer-bar${ratio>.85?' full':''}"><i style="width:${Math.round(ratio*100)}%"></i></span><span class="buffer-label">буфер</span> <b class="buffer-value">${fmt(buffer.qty)} / ${buffer.capacity}</b></div>`;}else card+='<div class="stage-buffer empty"></div>';
    card+='</div>';
    let link='';if(next){const stopped=['down','idle'].includes(k.status)||['down','idle'].includes(next.kpi.status),rate=Math.max(.1,Math.min(k.load_pct??100,next.kpi.load_pct??100)/100),dur=1.5/rate,phase=(now*rate/1.5+i*.2)%1;link=`<span class="flow-link${stopped?' stopped':''}" aria-hidden="true"><i style="animation-duration:${dur.toFixed(2)}s;animation-delay:${(-phase*dur).toFixed(2)}s"></i></span>`;}
    html+=`<div class="stage-cell">${card}${link}</div>`;});
  return html+'</div>';}
export function updatePlant(plant,force=false){if(historical&&!force)return;currentPlant=plant;const state=plant.state,stages=Object.values(state.stages),a=state.stages.assembly,limiting=[...stages].sort((a,b)=>(a.rate_per_hour*(1-a.defect_pct/100)-b.rate_per_hour*(1-b.defect_pct/100))||(Number(a.status!=='down')-Number(b.status!=='down')))[0];
  if($('#plant-kpis'))$('#plant-kpis').innerHTML=kpi('Выпуск сборки',fmt(a.fact),'авто',`Демо-сутки · план ${a.plan}`,'▱')+kpi('OEE потока · LIVE',fmt(limiting?.oee,1),'%',`Оперативная модель · цель ≥85%`,'◴',limiting?.oee<85?'yellow':'')+kpi('Брак на окраске',fmt(state.stages.painting.defect_pct,2),'%',`Допуск ≤2% · демо-поток`,'◉','red')+kpi('Простои участков',fmt(stages.reduce((s,x)=>s+x.downtime_min,0)),'мин','Сумма остановок · демо','◷')+kpi('Активные инциденты',fmt(state.incident_count),'',`Исходные данные + симуляция`,'△',state.incident_count?'yellow':'');
  if($('#plant-map'))$('#plant-map').innerHTML=mapHTML(plant);
  if($('#virtual-clock'))$('#virtual-clock').textContent=`Демо · ${state.at.slice(8,10)} окт, ${formatTime(state.at)}`;
}
export async function loadPlant(){const [plant,simulation,dashboard]=await Promise.all([api('/api/plant'),api('/api/simulation'),api('/api/dashboard')]);updatePlant(plant);if($('#simulation-toggle'))$('#simulation-toggle').checked=simulation.enabled;document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',+b.dataset.speed===simulation.speed));renderInsights(dashboard.decisions);await refreshTimeline();return plant;}
export function renderInsights(items){if(!$('#plant-insights'))return;$('#plant-insights').innerHTML=items.slice(0,2).map(i=>`<div class="insight-row"><div class="insight-icon">!</div><div><h3>${esc(i.title)}</h3><p>${esc(i.description)}</p></div><button class="button link" data-open-stage="${esc(i.stage||'painting')}" aria-label="Открыть ${esc(i.stage_name)}">↗</button></div>`).join('')||empty('Активных отклонений нет');}
export async function refreshTimeline(){if(!$('#timeline-slider'))return;const t=await api('/api/timeline');historyTimes=t.available;const slider=$('#timeline-slider');if(slider){slider.max=Math.max(0,historyTimes.length-1);if(!historical)slider.value=slider.max;}}
export async function selectSnapshot(index){if(!historyTimes[index])return;const t=await api('/api/timeline?at='+encodeURIComponent(historyTimes[index]));historical=true;updatePlant(t.plant,true);$('#timeline-time').textContent=formatTime(t.at);$('#snapshot-banner').innerHTML=`<div class="snapshot-banner">◷ Снимок ${dateLabel(t.at)} · отображение зафиксировано. Детализация участков содержит исходную историю; вернитесь «В эфир» для текущего потока.</div>`;}
export function showLive(){historical=false;if($('#snapshot-banner'))$('#snapshot-banner').innerHTML='';if($('#timeline-time'))$('#timeline-time').textContent='LIVE';return loadPlant();}
export async function showStage(code,includeSynthetic=false){openPanel(panelTop(names[code]||code)+loading());try{const d=await api('/api/stages/'+encodeURIComponent(code));const s=currentPlant?.stages.find(x=>x.code===code);let html=panelTop(d.stage.name);
    if(d.is_demo){const k=s?.kpi||{};html+=`${demo}<p class="subtitle">Упрощённая модель ${code==='quality'?'контроля качества':'склада'}.</p><div class="value-large section-space">${fmt(k.inventory)} <small>${code==='parts'?'комплектов':'единиц'}</small></div><div class="notice info">Остатки и движение заданы симулятором. Реальных складских записей и результатов финального контроля в кейсе нет.</div>`;html+=(s?.equipment||[]).map(e=>`<button class="button" data-equipment="${esc(e.code)}">${esc(e.code)} ↗</button>`).join('');openPanel(html);return;}
    const k=d.kpi.stages[0],p=d.production.filter(r=>includeSynthetic||!r.is_synthetic),q=d.quality.filter(r=>includeSynthetic||!r.is_synthetic),downs=d.downtime.filter(r=>includeSynthetic||!r.is_synthetic);
    html+=`<div class="detail-meta"><div>Исходный период<strong>01–02 октября 2026</strong></div><div>Смена<strong>Не указана в кейсе</strong></div></div><div class="kpi-strip">${kpi('План / факт',`${k.fact}`,'',`План ${k.plan} · ${fmt(k.performance,1)}%`)}${kpi('Загрузка',fmt(k.load_pct,1),'%','Среднее за 2 дня')}${kpi('Простой',fmt(k.downtime_min),'мин','Минуты оборудования')}${kpi('Брак',fmt(k.defect_pct,2),'%',`${k.defects} из ${k.fact}`,'',k.defect_pct>2?'red':'')}${kpi('OEE кейса',fmt(k.oee,2),'%','По методике задания')}${kpi('Годные',fmt(k.good),'ед.','На данном переделе')}</div><div class="notice info">${esc(d.kpi.methodology)} Плановое ТО не вычитается повторно из указанного времени работы.</div><label class="switch-label small-text muted"><input id="history-toggle" type="checkbox" data-history-stage="${code}" ${includeSynthetic?'checked':''}>Показать 60 дней синтетической истории</label><div class="detail-section"><h3>План и факт ${includeSynthetic?'· синтетическая история + кейс':''}</h3><div class="chart-legend"><span><i class="plan"></i>План</span><span><i></i>Факт</span></div>${lineChart(p,[{key:'plan',label:'План',color:'#8e9bb1'},{key:'fact',label:'Факт'}])}</div><div class="detail-section"><h3>Доля брака</h3>${lineChart(q,[{key:'defect_pct',label:'Брак, %'}],{threshold:2,height:175})}</div><div class="detail-section"><h3>Оборудование</h3><div class="filters">${(s?.equipment||[]).map(e=>`<button class="button small" data-equipment="${esc(e.code)}">${esc(e.code)} ↗</button>`).join('')}</div></div><div class="detail-section"><h3>Простои оборудования</h3>${downs.length?`<div class="table-scroll"><table><thead><tr><th>Дата</th><th>Причина</th><th>Мин</th></tr></thead><tbody>${downs.slice(0,15).map(r=>`<tr><td>${r.started_at.slice(0,10)}<br>${r.is_synthetic?badge('synthetic','Синтетика'):r.is_demo?demo:''}</td><td>${esc(r.reason)}<br>${r.kind==='planned'?badge('maintenance','Плановое ТО'):''}</td><td>${fmt(r.duration_min)}</td></tr>`).join('')}</tbody></table></div>`:empty()}</div><div class="detail-section"><h3>Инциденты участка</h3>${d.incidents.filter(i=>i.status!=='resolved').slice(0,4).map(i=>`<div class="insight-row"><div><h3>${esc(i.title)}</h3><p>${esc(i.description)}</p></div>${badge(i.severity)}</div>`).join('')||empty()}</div><div class="detail-section"><h3>Прогноз ИИ</h3>${aiNotice}${d.forecast.slice(0,2).map(r=>`<div class="risk-card"><div class="risk-head"><strong>${esc(r.equipment)}</strong>${badge(r.risk_level,fmt(r.probability*100,1)+'% / 24 ч')}</div>${r.factors.map(f=>`<div class="risk-factor"><span>${esc(f.name)}</span><span>${fmt(f.value,1)} · ${esc(f.direction)}</span></div>`).join('')}</div>`).join('')}</div>`;
    openPanel(html);
  }catch(e){openPanel(panelTop(names[code]||code)+error(e));}}
export async function showEquipment(code){openPanel(panelTop(code)+loading());try{const d=await api('/api/equipment/'+encodeURIComponent(code));openPanel(panelTop(d.name)+badge(d.status)+` <span class="badge demo">Справочник · демо</span><div class="detail-meta section-space"><div>Критическое<strong>${d.critical?'Да · допущение':'Нет'}</strong></div><div>Последнее ТО<strong>${d.last_maintenance_at.slice(0,10)}</strong></div><div>После ТО<strong>${fmt(d.hours_since_maintenance)} ч</strong></div><div>MTBF · допущение<strong>${fmt(d.mtbf_hours)} ч</strong></div></div><div class="detail-section"><h3>Риск простоя в следующие 24 часа</h3>${aiNotice}<div class="value-large">${fmt(d.risk?.probability*100,1)}<small>%</small></div><p class="subtitle">${d.risk?.currently_down?'Оборудование уже остановлено. Вероятность модели не является оценкой текущего статуса.':'Сохранённая оценка демонстрационной модели.'}</p>${(d.risk?.factors||[]).map(f=>`<div class="risk-factor"><span>${esc(f.name)}</span><span>${fmt(f.value,1)} · ${esc(f.direction)}</span></div>`).join('')}</div><div class="detail-section"><h3>История простоев</h3><div class="table-scroll"><table><thead><tr><th>Дата</th><th>Причина</th><th>Мин</th></tr></thead><tbody>${d.downtime.map(r=>`<tr><td>${r.started_at.slice(0,10)}<br>${r.is_synthetic?badge('synthetic','Синтетика'):r.is_demo?demo:badge('info','Кейс')}</td><td>${esc(r.reason)}<br>${r.kind==='planned'?badge('maintenance'):''}</td><td>${fmt(r.duration_min)}</td></tr>`).join('')||'<tr><td colspan="3">Событий нет</td></tr>'}</tbody></table></div></div>`);}catch(e){openPanel(panelTop(code)+error(e));}}
