import {$,esc,closePanel} from './ui.js';
let index=0,actions;
const steps=[['Весь завод на одном экране','Покажите участки, живой поток, оборудование и буферы. LIVE использует отдельную демонстрационную смену.','plant'],['Качество окраски','В исходных данных 10 дефектов из 231 изделия: 4,33% при допуске 2%. Откройте причины и обратите внимание на допущение OEE.','painting'],['Поломка конвейера и каскад','Сборка остановлена. На скорости ×20 буфер после окраски растёт, затем ограничивает окраску и сварку. Понаблюдайте несколько тиков.','scenario'],['Объяснимый прогноз','Покажите риск оборудования, вклад факторов и прогноз выпуска. Модель обучена на синтетической истории; производственная точность не заявляется.','forecast'],['Измеримый эффект','Измените стоимость простоя и ожидаемое улучшение. Покажите годовую оценку, окупаемость и допущения расчёта.','impact']];
async function show(){const [title,text,action]=steps[index];closePanel();if(action==='painting'){await actions.navigate('plant');await actions.stage('painting');}else if(action==='scenario'){await actions.navigate('plant');await actions.simulation({enabled:true,speed:20});await actions.scenario('conveyor_failure');}else await actions.navigate(action);
  $('#presentation').classList.remove('hidden');$('#presentation').innerHTML=`<div class="eyebrow">ДЕМОНСТРАЦИЯ · ШАГ ${index+1} ИЗ 5</div><h2>${esc(title)}</h2><p>${esc(text)}</p><div class="presentation-actions"><button class="button small ghost" id="tour-exit">Завершить</button><div><button class="button small" id="tour-back" ${index===0?'disabled':''}>←</button> <button class="button small primary" id="tour-next">${index===4?'Готово':'Далее →'}</button></div></div>`;
  $('#tour-exit').onclick=stop;$('#tour-back').onclick=()=>{if(index>0){index--;show();}};$('#tour-next').onclick=()=>{if(index===4){stop();return;}index++;show();};
}
export function startPresentation(callbacks){actions=callbacks;index=0;return show();}
export function stop(){$('#presentation').classList.add('hidden');}
